FROM node:lts-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

ARG PORT
ENV PORT=${PORT}

ARG MONGO_URI
ENV MONGO_URI=${MONGO_URI}

ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

ARG GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

ARG GOOGLE_REDIRECT_URL
ENV GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}


ARG GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}

ARG GITHUB_CLIENT_SECRET
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}


ARG MAILTRAP_USER
ENV MAILTRAP_USER=${MAILTRAP_USER}

ARG MAILTRAP_PASSWORD
ENV MAILTRAP_PASSWORD=${MAILTRAP_PASSWORD}

ARG CLOUDINARY_CLOUD_NAME
ENV CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}

ARG CLOUDINARY_API_KEY
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}

ARG CLOUDINARY_API_SECRET
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}


EXPOSE 3000

RUN npm run build

CMD ["npm", "run", "start:production"]